-- MySQL Script generated by MySQL Workbench
-- Tue Apr 16 22:38:53 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sportswear_store
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sportswear_store
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sportswear_store` DEFAULT CHARACTER SET utf8mb4 ;
USE `sportswear_store` ;

-- -----------------------------------------------------
-- Table `sportswear_store`.`Lugar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportswear_store`.`Lugar` (
  `Codigo` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Lugar_Codigo` INT NOT NULL,
  PRIMARY KEY (`Codigo`),
  INDEX `fk_Lugar_Lugar1_idx` (`Lugar_Codigo` ASC),
  UNIQUE INDEX `Lugar_Codigo_UNIQUE` (`Lugar_Codigo` ASC),
  CONSTRAINT `fk_Lugar_Lugar1`
    FOREIGN KEY (`Lugar_Codigo`)
    REFERENCES `sportswear_store`.`Lugar` (`Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportswear_store`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportswear_store`.`Persona` (
  `Identificacion` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  `Genero` ENUM('Hombre', 'Mujer') NULL,
  `Edad` INT NULL,
  `Lugar_Codigo` INT NOT NULL,
  PRIMARY KEY (`Identificacion`),
  INDEX `fk_Persona_Lugar1_idx` (`Lugar_Codigo` ASC),
  CONSTRAINT `fk_Persona_Lugar1`
    FOREIGN KEY (`Lugar_Codigo`)
    REFERENCES `sportswear_store`.`Lugar` (`Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportswear_store`.`Cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportswear_store`.`Cuenta` (
  `Usuario` VARCHAR(50) NOT NULL,
  `Tipo_Cuenta` ENUM('Administrador', 'Cliente') NOT NULL,
  `Contraseña` VARCHAR(45) NOT NULL,
  `Usuario_Identificacion` INT NOT NULL,
  PRIMARY KEY (`Usuario`),
  INDEX `fk_Cuenta_Usuario1_idx` (`Usuario_Identificacion` ASC),
  CONSTRAINT `fk_Cuenta_Usuario1`
    FOREIGN KEY (`Usuario_Identificacion`)
    REFERENCES `sportswear_store`.`Persona` (`Identificacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportswear_store`.`Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportswear_store`.`Compra` (
  `ID_compra` INT NOT NULL AUTO_INCREMENT,
  `Costo_total` DECIMAL(10,2) NOT NULL,
  `Fecha_compra` DATE NOT NULL,
  `Cuenta_Usuario` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID_compra`),
  INDEX `fk_Compra_Cuenta1_idx` (`Cuenta_Usuario` ASC),
  CONSTRAINT `fk_Compra_Cuenta1`
    FOREIGN KEY (`Cuenta_Usuario`)
    REFERENCES `sportswear_store`.`Cuenta` (`Usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportswear_store`.`Envio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportswear_store`.`Envio` (
  `ID_envio` INT NOT NULL AUTO_INCREMENT,
  `Direccion` VARCHAR(45) NOT NULL,
  `Fecha_envio` DATE NOT NULL,
  `Codigo_postal` INT NOT NULL,
  `Compra_ID_compra` INT NOT NULL,
  `Lugar_Codigo` INT NOT NULL,
  PRIMARY KEY (`ID_envio`),
  INDEX `fk_Envio_Compra1_idx` (`Compra_ID_compra` ASC),
  INDEX `fk_Envio_Lugar1_idx` (`Lugar_Codigo` ASC),
  CONSTRAINT `fk_Envio_Compra1`
    FOREIGN KEY (`Compra_ID_compra`)
    REFERENCES `sportswear_store`.`Compra` (`ID_compra`),
  CONSTRAINT `fk_Envio_Lugar1`
    FOREIGN KEY (`Lugar_Codigo`)
    REFERENCES `sportswear_store`.`Lugar` (`Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportswear_store`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportswear_store`.`Producto` (
  `Identificacion` INT NOT NULL AUTO_INCREMENT,
  `Precio` DECIMAL(10,2) NOT NULL,
  `Imagen_producto` BLOB NOT NULL,
  `Tipo_Producto` ENUM('Articulo', 'Diseño') NOT NULL,
  `Tipo_Articulo` ENUM('Calcetines', 'Polo', 'Zapatillas', 'Gorra', 'Pantalon', 'Camisa') NULL,
  `Seccion_Articulo` ENUM('Hombre', 'Mujer', 'Nino') NULL,
  `Cantidad_Articulo` INT NULL,
  `Especificaciones_Articulo` JSON NULL,
  `Productos_paquete` JSON NULL,
  `esPaquete` TINYINT NULL,
  PRIMARY KEY (`Identificacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportswear_store`.`Contiene`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportswear_store`.`Contiene` (
  `ID_contiene` INT NOT NULL AUTO_INCREMENT,
  `Producto_Identificacion` INT NOT NULL,
  `Compra_ID_compra` INT NOT NULL,
  `Cantidad` INT NOT NULL,
  `Especificaciones` JSON NULL,
  INDEX `fk_Producto_has_Compra_Compra1_idx` (`Compra_ID_compra` ASC),
  INDEX `fk_Producto_has_Compra_Producto1_idx` (`Producto_Identificacion` ASC),
  PRIMARY KEY (`ID_contiene`),
  CONSTRAINT fk_Producto_has_Compra_Producto1
    FOREIGN KEY (Producto_Identificacion)
    REFERENCES Sportswear_Store.Producto (Identificacion),
  CONSTRAINT fk_Producto_has_Compra_Compra1
    FOREIGN KEY (Compra_ID_compra)
    REFERENCES Sportswear_Store.Compra (ID_compra))
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;