-- MySQL Script generated by MySQL Workbench
-- Mon Mar  4 09:49:51 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sportswear_store
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sportswear_store
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sportswear_store
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sportswear_store` ;
USE `sportswear_store` ;

-- -----------------------------------------------------
-- Table `sportswear_store`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportswear_store`.`Usuario` (
  `Identificacion` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  `Correo` VARCHAR(50) NOT NULL,
  `Telefono` INT NOT NULL,
  `Genero` ENUM('H', 'M') NOT NULL,
  `Edad` INT NOT NULL,
  `TipoUsuario` ENUM('Cliente', 'Administrador') NOT NULL,
  PRIMARY KEY (`Identificacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportswear_store`.`Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportswear_store`.`Compra` (
  `ID_compra` INT NOT NULL AUTO_INCREMENT,
  `Costo_total` DECIMAL(2) NOT NULL,
  `Fecha compra` DATE NOT NULL,
  `UCliente_Identificacion` INT NOT NULL,
  PRIMARY KEY (`ID_compra`),
  INDEX `fk_Compra_UCliente1_idx` (`UCliente_Identificacion` ASC) VISIBLE,
  CONSTRAINT `fk_Compra_UCliente1`
    FOREIGN KEY (`UCliente_Identificacion`)
    REFERENCES `sportswear_store`.`Usuario` (`Identificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportswear_store`.`Lugar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportswear_store`.`Lugar` (
  `Codigo` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Lugar_Codigo` INT NOT NULL,
  PRIMARY KEY (`Codigo`),
  INDEX `fk_Lugar_Lugar1_idx` (`Lugar_Codigo` ASC) VISIBLE,
  CONSTRAINT `fk_Lugar_Lugar1`
    FOREIGN KEY (`Lugar_Codigo`)
    REFERENCES `sportswear_store`.`Lugar` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportswear_store`.`Envio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportswear_store`.`Envio` (
  `ID_Envio` INT NOT NULL AUTO_INCREMENT,
  `Direccion` VARCHAR(50) NOT NULL,
  `Fecha_envio` VARCHAR(50) NOT NULL,
  `Codigopostal` INT NOT NULL,
  `Compra_ID_compra` INT NOT NULL,
  `Lugar_Codigo` INT NOT NULL,
  PRIMARY KEY (`ID_Envio`),
  INDEX `fk_Envio_Compra1_idx` (`Compra_ID_compra` ASC) VISIBLE,
  INDEX `fk_Envio_Lugar1_idx` (`Lugar_Codigo` ASC) VISIBLE,
  CONSTRAINT `fk_Envio_Compra1`
    FOREIGN KEY (`Compra_ID_compra`)
    REFERENCES `sportswear_store`.`Compra` (`ID_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Envio_Lugar1`
    FOREIGN KEY (`Lugar_Codigo`)
    REFERENCES `sportswear_store`.`Lugar` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportswear_store`.`Articulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportswear_store`.`Articulo` (
  `Identificacion` INT NOT NULL AUTO_INCREMENT,
  `Tipoproducto` ENUM('Articulo', 'Diseño') NOT NULL,
  `Precio` DECIMAL(2) NOT NULL,
  `Imagen del producto` BLOB NOT NULL,
  `Secciones` ENUM('H', 'M', 'N') NULL,
  `Cantidad` INT NULL,
  `TipoArticulo` VARCHAR(45) NULL,
  PRIMARY KEY (`Identificacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportswear_store`.`Contiene`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportswear_store`.`Contiene` (
  `PArticulo_Identificacion` INT NOT NULL,
  `Compra_ID_compra` INT NOT NULL,
  `Cantidad` INT NOT NULL,
  PRIMARY KEY (`PArticulo_Identificacion`, `Compra_ID_compra`),
  INDEX `fk_PArticulo_has_Compra_Compra1_idx` (`Compra_ID_compra` ASC) VISIBLE,
  INDEX `fk_PArticulo_has_Compra_PArticulo1_idx` (`PArticulo_Identificacion` ASC) VISIBLE,
  CONSTRAINT `fk_PArticulo_has_Compra_PArticulo1`
    FOREIGN KEY (`PArticulo_Identificacion`)
    REFERENCES `sportswear_store`.`Articulo` (`Identificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PArticulo_has_Compra_Compra1`
    FOREIGN KEY (`Compra_ID_compra`)
    REFERENCES `sportswear_store`.`Compra` (`ID_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportswear_store`.`ResenaArticulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportswear_store`.`ResenaArticulo` (
  `ID_resenaA` INT NOT NULL,
  `Comentarios` VARCHAR(100) NOT NULL,
  `Valoraciones` DECIMAL(1) NOT NULL,
  `Articulo_Identificacion` INT NOT NULL,
  PRIMARY KEY (`ID_resenaA`, `Articulo_Identificacion`),
  INDEX `fk_ResenaArticulo_Articulo1_idx` (`Articulo_Identificacion` ASC) VISIBLE,
  CONSTRAINT `fk_ResenaArticulo_Articulo1`
    FOREIGN KEY (`Articulo_Identificacion`)
    REFERENCES `sportswear_store`.`Articulo` (`Identificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportswear_store`.`Paquete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportswear_store`.`Paquete` (
  `ID_Paquete` INT NOT NULL AUTO_INCREMENT,
  `Precio` DECIMAL(2) NULL,
  PRIMARY KEY (`ID_Paquete`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportswear_store`.`Almacena`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportswear_store`.`Almacena` (
  `Paquete_ID_Paquete` INT NOT NULL,
  `Articulo_Identificacion` INT NOT NULL,
  PRIMARY KEY (`Paquete_ID_Paquete`, `Articulo_Identificacion`),
  INDEX `fk_Paquete_has_Articulo_Articulo1_idx` (`Articulo_Identificacion` ASC) VISIBLE,
  INDEX `fk_Paquete_has_Articulo_Paquete1_idx` (`Paquete_ID_Paquete` ASC) VISIBLE,
  CONSTRAINT `fk_Paquete_has_Articulo_Paquete1`
    FOREIGN KEY (`Paquete_ID_Paquete`)
    REFERENCES `sportswear_store`.`Paquete` (`ID_Paquete`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Paquete_has_Articulo_Articulo1`
    FOREIGN KEY (`Articulo_Identificacion`)
    REFERENCES `sportswear_store`.`Articulo` (`Identificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;